In [1]:
import pandas as pd

In [4]:
events = pd.read_parquet('../interim/data_events.parquet')
fed = pd.read_parquet('../interim/data_fed.parquet')
stocks = pd.read_parquet('../interim/data_stocks.parquet')
event_day = pd.read_parquet('../interim/event_day_countdown.parquet')

In [7]:
events.head(1)

event,US Advance GDP q/q,US Average Hourly Earnings m/m,US Building Permits,US CPI m/m,US CPI y/y,US Core CPI m/m,US Core PCE Price Index m/m,US Core Retail Sales m/m,US Existing Home Sales,US Federal Funds Rate,...,US ISM Manufacturing PMI,US ISM Services PMI,US New Home Sales,US Non-Farm Employment Change,US PPI m/m,US Personal Income m/m,US Personal Spending m/m,US Prelim GDP q/q,US Retail Sales m/m,US Unemployment Rate
date,,,,,,,,,,,,,,,,,,,,,
2007-03-29,0.035,0.004,1530000.0,0.004,0.024,0.002,0.003,-0.001,6690000.0,0.0525,...,52.3,54.3,848000.0,97000.0,0.013,0.01,0.005,0.022,0.001,0.045

In [8]:
fed.head(1)

,FEDFUNDS,DFF,T10Y2Y,T10Y3M,GS10,GS2,BAMLH0A0HYM2,BAMLC0A0CM,NFCI,UNRATE,CPIAUCSL,T5YIE,T10YIE,ICSA,WALCL,M2SL,TEDRATE
2003-01-02,1.24,1.3,2.27,2.85,4.05,1.74,8.65,1.86,-0.46631,5.9,181.8,1.3,1.64,409000.0,732059.0,5779.4,0.18

In [9]:
stocks.head(1)

,spy_open,spy_high,spy_low,spy_close,spy_volume,spy_EMA_14,spy_EMA_30,spy_EMA_60,spy_SMA_14,spy_SMA_30,...,gc=f_RSI_21,gc=f_RSI_30,gc=f_MACD,gc=f_MACD_signal,gc=f_MACD_hist,gc=f_AROON_down,gc=f_AROON_up,gc=f_MFI,gc=f_AVGPRICE,gc=f_MEDPRICE
date,,,,,,,,,,,,,,,,,,,,,
2000-11-22,85.25717,85.594312,83.849108,83.859024,5736900.0,87.105937,88.180085,89.488997,87.849456,87.919243,...,45.996707,45.22616,-0.904852,-1.352472,0.447621,50.0,100.0,2.741513,266.299988,266.299988

In [10]:
event_day.head(1)

event,US FOMC Economic Projections,US FOMC Press Conference,US FOMC Statement
date,,,
2007-01-31,1547,1547,0

In [13]:
df = pd.concat([events, fed, stocks, event_day], axis=1, sort=True).dropna(how='any')
df.head()

,US Advance GDP q/q,US Average Hourly Earnings m/m,US Building Permits,US CPI m/m,US CPI y/y,US Core CPI m/m,US Core PCE Price Index m/m,US Core Retail Sales m/m,US Existing Home Sales,US Federal Funds Rate,...,gc=f_MACD_signal,gc=f_MACD_hist,gc=f_AROON_down,gc=f_AROON_up,gc=f_MFI,gc=f_AVGPRICE,gc=f_MEDPRICE,US FOMC Economic Projections,US FOMC Press Conference,US FOMC Statement
2007-03-29,0.035,0.004,1530000.0,0.004,0.024,0.002,0.003,-0.001,6690000.0,0.0525,...,0.895778,1.175966,21.428571,92.857143,21.635926,662.050003,660.399994,1490.0,1490.0,41.0
2007-03-30,0.035,0.004,1530000.0,0.004,0.024,0.002,0.003,-0.001,6690000.0,0.0525,...,1.161384,1.062423,14.285714,100.000000,28.540917,662.750000,663.399994,1489.0,1489.0,40.0
2007-04-02,0.035,0.004,1530000.0,0.004,0.024,0.002,0.003,-0.001,6690000.0,0.0525,...,1.435704,1.097282,7.142857,92.857143,27.775431,663.199997,660.799988,1486.0,1486.0,37.0
2007-04-04,0.035,0.004,1530000.0,0.004,0.024,0.002,0.003,-0.001,6690000.0,0.0525,...,1.994182,1.293880,0.000000,100.000000,30.387048,668.774994,669.500000,1484.0,1484.0,35.0
2007-04-13,0.035,0.003,1530000.0,0.004,0.024,0.002,0.003,-0.001,6690000.0,0.0525,...,4.358484,1.789605,28.571429,100.000000,30.706577,682.350006,681.899994,1475.0,1475.0,26.0

In [14]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2263 entries, 2007-03-29 to 2026-02-20
Columns: 167 entries, US Advance GDP q/q to US FOMC Statement
dtypes: float64(167)
memory usage: 2.9 MB

In [19]:
print(df.columns.tolist())

['US Advance GDP q/q', 'US Average Hourly Earnings m/m', 'US Building Permits', 'US CPI m/m', 'US CPI y/y', 'US Core CPI m/m', 'US Core PCE Price Index m/m', 'US Core Retail Sales m/m', 'US Existing Home Sales', 'US Federal Funds Rate', 'US Final GDP q/q', 'US Housing Starts', 'US ISM Manufacturing PMI', 'US ISM Services PMI', 'US New Home Sales', 'US Non-Farm Employment Change', 'US PPI m/m', 'US Personal Income m/m', 'US Personal Spending m/m', 'US Prelim GDP q/q', 'US Retail Sales m/m', 'US Unemployment Rate', 'FEDFUNDS', 'DFF', 'T10Y2Y', 'T10Y3M', 'GS10', 'GS2', 'BAMLH0A0HYM2', 'BAMLC0A0CM', 'NFCI', 'UNRATE', 'CPIAUCSL', 'T5YIE', 'T10YIE', 'ICSA', 'WALCL', 'M2SL', 'TEDRATE', 'spy_open', 'spy_high', 'spy_low', 'spy_close', 'spy_volume', 'spy_EMA_14', 'spy_EMA_30', 'spy_EMA_60', 'spy_SMA_14', 'spy_SMA_30', 'spy_SMA_60', 'spy_BB_upper', 'spy_BB_middle', 'spy_BB_lower', 'spy_RSI_14', 'spy_RSI_21', 'spy_RSI_30', 'spy_MACD', 'spy_MACD_signal', 'spy_MACD_hist', 'spy_AROON_down', 'spy_AROON_up', 'spy_MFI', 'spy_AVGPRICE', 'spy_MEDPRICE', 'qqq_open', 'qqq_high', 'qqq_low', 'qqq_close', 'qqq_volume', 'qqq_EMA_14', 'qqq_EMA_30', 'qqq_EMA_60', 'qqq_SMA_14', 'qqq_SMA_30', 'qqq_SMA_60', 'qqq_BB_upper', 'qqq_BB_middle', 'qqq_BB_lower', 'qqq_RSI_14', 'qqq_RSI_21', 'qqq_RSI_30', 'qqq_MACD', 'qqq_MACD_signal', 'qqq_MACD_hist', 'qqq_AROON_down', 'qqq_AROON_up', 'qqq_MFI', 'qqq_AVGPRICE', 'qqq_MEDPRICE', '^vix_open', '^vix_high', '^vix_low', '^vix_close', '^vix_volume', '^vix_EMA_14', '^vix_EMA_30', '^vix_EMA_60', '^vix_SMA_14', '^vix_SMA_30', '^vix_SMA_60', '^vix_BB_upper', '^vix_BB_middle', '^vix_BB_lower', '^vix_RSI_14', '^vix_RSI_21', '^vix_RSI_30', '^vix_MACD', '^vix_MACD_signal', '^vix_MACD_hist', '^vix_AROON_down', '^vix_AROON_up', '^vix_MFI', '^vix_AVGPRICE', '^vix_MEDPRICE', 'dx-y.nyb_open', 'dx-y.nyb_high', 'dx-y.nyb_low', 'dx-y.nyb_close', 'dx-y.nyb_volume', 'dx-y.nyb_EMA_14', 'dx-y.nyb_EMA_30', 'dx-y.nyb_EMA_60', 'dx-y.nyb_SMA_14', 'dx-y.nyb_SMA_30', 'dx-y.nyb_SMA_60', 'dx-y.nyb_BB_upper', 'dx-y.nyb_BB_middle', 'dx-y.nyb_BB_lower', 'dx-y.nyb_RSI_14', 'dx-y.nyb_RSI_21', 'dx-y.nyb_RSI_30', 'dx-y.nyb_MACD', 'dx-y.nyb_MACD_signal', 'dx-y.nyb_MACD_hist', 'dx-y.nyb_AROON_down', 'dx-y.nyb_AROON_up', 'dx-y.nyb_MFI', 'dx-y.nyb_AVGPRICE', 'dx-y.nyb_MEDPRICE', 'gc=f_open', 'gc=f_high', 'gc=f_low', 'gc=f_close', 'gc=f_volume', 'gc=f_EMA_14', 'gc=f_EMA_30', 'gc=f_EMA_60', 'gc=f_SMA_14', 'gc=f_SMA_30', 'gc=f_SMA_60', 'gc=f_BB_upper', 'gc=f_BB_middle', 'gc=f_BB_lower', 'gc=f_RSI_14', 'gc=f_RSI_21', 'gc=f_RSI_30', 'gc=f_MACD', 'gc=f_MACD_signal', 'gc=f_MACD_hist', 'gc=f_AROON_down', 'gc=f_AROON_up', 'gc=f_MFI', 'gc=f_AVGPRICE', 'gc=f_MEDPRICE', 'US FOMC Economic Projections', 'US FOMC Press Conference', 'US FOMC Statement']

In [20]:
df.to_parquet('../processed/data.parquet')