In [2]:
import sqlalchemy as db
import pandas as pd

In [1]:

engine = db.create_engine('sqlite:///../raw/data.db')

In [14]:
data_stocks = pd.read_sql('SELECT * FROM Stocks WHERE date >= (SELECT MIN(date) FROM Events)', con=engine) #equals the first date with events
data_fed = pd.read_sql('SELECT * FROM Macro WHERE date >= (SELECT MIN(date) FROM Events)', con=engine) #equals the first date with events
data_events = pd.read_sql('SELECT * FROM Events', con=engine)

In [15]:
data_stocks.head()

,date,ticker,open,high,low,close,volume
0,2007-01-03 00:00:00.000000,DX-Y.NYB,83.269997,84.040001,83.169998,83.919998,0
1,2007-01-03 00:00:00.000000,GC=F,640.400024,640.400024,628.500000,627.099976,38
2,2007-01-03 00:00:00.000000,QQQ,37.315239,37.830407,36.508146,37.126347,167689500
3,2007-01-03 00:00:00.000000,SPY,100.013622,100.442503,98.832447,99.394905,94807600
4,2007-01-03 00:00:00.000000,^VIX,12.160000,12.750000,11.530000,12.040000,0

In [21]:
data_stocks.info()

<class 'pandas.DataFrame'>
RangeIndex: 24070 entries, 0 to 24069
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    24070 non-null  str
 1   ticker  24070 non-null  str
 2   open    24070 non-null  float64
 3   high    24070 non-null  float64
 4   low     24070 non-null  float64
 5   close   24070 non-null  float64
 6   volume  24070 non-null  int64
dtypes: float64(4), int64(1), str(2)
memory usage: 1.3 MB

In [23]:
data_fed.head()

                         date         serie  value
0  2007-01-03 00:00:00.000000    BAMLC0A0CM   0.91
1  2007-01-03 00:00:00.000000  BAMLH0A0HYM2   2.91
2  2007-01-03 00:00:00.000000           DFF   5.28
3  2007-01-03 00:00:00.000000        T10Y2Y  -0.09
4  2007-01-03 00:00:00.000000        T10Y3M  -0.38

In [22]:
data_fed.info()

<class 'pandas.DataFrame'>
RangeIndex: 46155 entries, 0 to 46154
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    46155 non-null  str
 1   serie   46155 non-null  str
 2   value   46155 non-null  float64
dtypes: float64(1), str(2)
memory usage: 1.1 MB

In [19]:
data_events.head()

                         date                        event actual previous
0  2007-01-03 00:00:00.000000        ISM Manufacturing PMI   51.4     49.5
1  2007-01-04 00:00:00.000000             ISM Services PMI   57.1     58.9
2  2007-01-05 00:00:00.000000   Non-Farm Employment Change   167K     132K
3  2007-01-05 00:00:00.000000            Unemployment Rate   4.5%     4.5%
4  2007-01-05 00:00:00.000000  Average Hourly Earnings m/m   0.5%     0.3%

In [24]:
data_events.info()

<class 'pandas.DataFrame'>
RangeIndex: 2042 entries, 0 to 2041
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      2042 non-null   str
 1   event     2042 non-null   str
 2   actual    2042 non-null   str
 3   previous  2042 non-null   str
dtypes: str(4)
memory usage: 63.9 KB

In [28]:
data_events[data_events['event'] == 'Retail Sales m/m']

                            date             event actual previous
6     2007-01-12 00:00:00.000000  Retail Sales m/m   0.9%     1.0%
26    2007-02-14 00:00:00.000000  Retail Sales m/m   0.0%     1.2%
44    2007-03-13 00:00:00.000000  Retail Sales m/m   0.1%     0.0%
65    2007-04-16 00:00:00.000000  Retail Sales m/m   0.7%     0.5%
85    2007-05-11 00:00:00.000000  Retail Sales m/m  -0.2%     1.0%
...                          ...               ...    ...      ...
1946  2023-06-15 00:00:00.000000  Retail Sales m/m   0.3%     0.4%
1968  2024-06-18 00:00:00.000000  Retail Sales m/m   0.1%    -0.2%
1986  2025-06-17 00:00:00.000000  Retail Sales m/m  -0.9%    -0.1%
2011  2026-06-17 00:00:00.000000  Retail Sales m/m
2031  2026-07-16 00:00:00.000000  Retail Sales m/m

[103 rows x 4 columns]