In [1]:
import sqlalchemy as db
import pandas as pd

In [2]:

engine = db.create_engine('sqlite:///../raw/data.db')

In [12]:
data_stocks = pd.read_sql('SELECT * FROM Stocks)', con=engine) #equals the first date with events
data_fed = pd.read_sql('SELECT * FROM Macro)', con=engine) #equals the first date with events
data_events = pd.read_sql('SELECT * FROM Events', con=engine)

DatabaseError: Execution failed on sql 'SELECT * FROM Stocks)': (sqlite3.OperationalError) near ")": syntax error
[SQL: SELECT * FROM Stocks)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [4]:
data_stocks.head()

,date,ticker,open,high,low,close,volume
0,2007-01-03 00:00:00.000000,DX-Y.NYB,83.269997,84.040001,83.169998,83.919998,0
1,2007-01-03 00:00:00.000000,GC=F,640.400024,640.400024,628.500000,627.099976,38
2,2007-01-03 00:00:00.000000,QQQ,37.315231,37.830400,36.508138,37.126339,167689500
3,2007-01-03 00:00:00.000000,SPY,100.013637,100.442519,98.832462,99.394920,94807600
4,2007-01-03 00:00:00.000000,^VIX,12.160000,12.750000,11.530000,12.040000,0

In [5]:
data_stocks.info()

<class 'pandas.DataFrame'>
RangeIndex: 24077 entries, 0 to 24076
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    24077 non-null  str
 1   ticker  24077 non-null  str
 2   open    24077 non-null  float64
 3   high    24077 non-null  float64
 4   low     24077 non-null  float64
 5   close   24077 non-null  float64
 6   volume  24077 non-null  int64
dtypes: float64(4), int64(1), str(2)
memory usage: 1.3 MB

In [13]:
data_fed.head()

                         date         serie  value
0  2007-01-03 00:00:00.000000    BAMLC0A0CM   0.91
1  2007-01-03 00:00:00.000000  BAMLH0A0HYM2   2.91
2  2007-01-03 00:00:00.000000           DFF   5.28
3  2007-01-03 00:00:00.000000        T10Y2Y  -0.09
4  2007-01-03 00:00:00.000000        T10Y3M  -0.38

In [14]:
data_fed.info()

<class 'pandas.DataFrame'>
RangeIndex: 46163 entries, 0 to 46162
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    46163 non-null  str
 1   serie   46163 non-null  str
 2   value   46163 non-null  float64
dtypes: float64(1), str(2)
memory usage: 1.1 MB

In [15]:
data_events.head()

                  date                  event actual previous
0  2026-01-28 00:00:00  US Federal Funds Rate  3.75%    3.75%
1  2025-12-10 00:00:00  US Federal Funds Rate  3.75%    4.00%
2  2025-10-29 00:00:00  US Federal Funds Rate  4.00%    4.25%
3  2025-09-17 00:00:00  US Federal Funds Rate  4.25%    4.50%
4  2025-07-30 00:00:00  US Federal Funds Rate  4.50%    4.50%

In [16]:
data_events.info()

<class 'pandas.DataFrame'>
RangeIndex: 4794 entries, 0 to 4793
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      4794 non-null   str
 1   event     4794 non-null   str
 2   actual    4794 non-null   str
 3   previous  4794 non-null   str
dtypes: str(4)
memory usage: 149.9 KB

In [17]:
data_events[data_events['event'] == 'US Retail Sales m/m']

                     date                event actual previous
2515  2026-02-10 00:00:00  US Retail Sales m/m   0.0%     0.6%
2516  2026-01-14 00:00:00  US Retail Sales m/m   0.6%    -0.1%
2517  2025-12-16 00:00:00  US Retail Sales m/m   0.0%     0.1%
2518  2025-11-25 00:00:00  US Retail Sales m/m   0.2%     0.6%
2519  2025-09-16 00:00:00  US Retail Sales m/m   0.6%     0.6%
...                   ...                  ...    ...      ...
2739  2007-05-11 00:00:00  US Retail Sales m/m  -0.2%     1.0%
2740  2007-04-16 00:00:00  US Retail Sales m/m   0.7%     0.5%
2741  2007-03-13 00:00:00  US Retail Sales m/m   0.1%     0.0%
2742  2007-02-14 00:00:00  US Retail Sales m/m   0.0%     1.2%
2743  2007-01-12 00:00:00  US Retail Sales m/m   0.9%     1.0%

[229 rows x 4 columns]